---
attendees:
  hosts:
    attendee01: { attendee_number: 1 }
    attendee02: { attendee_number: 2 }
    attendee03: { attendee_number: 3 }
    attendee04: { attendee_number: 4 }
    attendee05: { attendee_number: 5 }
    attendee06: { attendee_number: 6 }
    attendee07: { attendee_number: 7 }
    attendee08: { attendee_number: 8 }
    attendee09: { attendee_number: 9 }
    attendee10: { attendee_number: 10 }
    attendee11: { attendee_number: 11 }
    attendee12: { attendee_number: 12 }
    attendee13: { attendee_number: 13 }
    attendee14: { attendee_number: 14 }
    attendee15: { attendee_number: 15 }
    attendee16: { attendee_number: 16 }
    attendee17: { attendee_number: 17 }
    attendee18: { attendee_number: 18 }
    attendee19: { attendee_number: 19 }
    attendee20: { attendee_number: 20 }
    attendee21: { attendee_number: 21 }
    attendee22: { attendee_number: 22 }
    attendee23: { attendee_number: 23 }
    attendee24: { attendee_number: 24 }
    attendee25: { attendee_number: 25 }
    attendee26: { attendee_number: 26 }
    attendee27: { attendee_number: 27 }
    attendee28: { attendee_number: 28 }
    attendee29: { attendee_number: 29 }
    attendee30: { attendee_number: 30 }
    attendee31: { attendee_number: 31 }
    attendee32: { attendee_number: 32 }
    attendee33: { attendee_number: 33 }
    attendee34: { attendee_number: 34 }
    attendee35: { attendee_number: 35 }
    attendee36: { attendee_number: 36 }
    attendee37: { attendee_number: 37 }
    attendee38: { attendee_number: 38 }
    attendee39: { attendee_number: 39 }
    attendee40: { attendee_number: 40 }
    attendee41: { attendee_number: 41 }
    attendee42: { attendee_number: 42 }
    attendee43: { attendee_number: 43 }
    attendee44: { attendee_number: 44 }
    attendee45: { attendee_number: 45 }
    attendee46: { attendee_number: 46 }
    attendee47: { attendee_number: 47 }
    attendee48: { attendee_number: 48 }
    attendee49: { attendee_number: 49 }
    attendee50: { attendee_number: 50 }
    attendee51: { attendee_number: 51 }
    attendee52: { attendee_number: 52 }
    attendee53: { attendee_number: 53 }
    attendee54: { attendee_number: 54 }
    attendee55: { attendee_number: 55 }
    attendee56: { attendee_number: 56 }
    attendee57: { attendee_number: 57 }
    attendee58: { attendee_number: 58 }
    attendee59: { attendee_number: 59 }
    attendee60: { attendee_number: 60 }
    instructor: { attendee_number: 99 }
